### DISCUSSION TITLE
Automatic switching to dark theme from browser settings

### DISCUSSION THREAD

**Discussion by krom** [alangrainger/share-note#112] [Vote for upcoming features]
For now, you can select a dark/light theme for a note in the plugin plugin and change it in the shared note.
![image](https://github.com/alangrainger/share-note/assets/970843/863c0f70-589b-4887-96a2-bfd745c97402)

my suggestion: be able to switch dark/light theme depending on browser settings eg.

Using CSS
```css
/* Light mode */
@media (prefers-color-scheme: light) {
    body {
        background-color: white;
        color: black;
    }
}
In case user preference is dark:

/* Dark mode */
@media (prefers-color-scheme: dark) {
    body {
        background-color: black;
        color: white;
    }
}
```
or
Using JavaScript
```javascript
if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
    // dark mode
}
```
