### ISSUE TITLE
Published note is not printable or exportable.

### ISSUE THREAD

**Issue by the1gofer** [alangrainger/share-note#75]
Once published, I am unable to print the entire shared note on Mac. I am also unable to use Safari to export the note as a PDF as a workaround. When printing the screen is blank, when exporting to PDF, only the visible section of the screen is generated into PDF.

I'm using the latest version of Obsidian in the latest version of your plug-in and I'm trying to export and print on Mac latest OS

**Comment by skakdollar** [comment]
Same here. Fantastic plugin overall.

**Comment by MicaelJarniac** [comment]
I'm also having this issue. I was trying to use this plugin exactly because I can't export to PDF from inside Obsidian either, for this one specific note. Sharing works, but I cannot then print from the shared page either.

**Comment by alangrainger** [comment]
I think it's something in the Obsidian CSS bundle which is saying "no printing allowed", but I'm not good enough with CSS to know what it could be.

Anyone have any ideas?

**Comment by texastoland** [comment]
I confirmed it's the following print media CSS:

```css

@media print {
    html, body {
        padding-top: 0px !important;
        overflow: auto !important;
        height: auto !important; /* cause */
    }

    iframe, .titlebar, .app-container, .progress-bar, .popover, .markdown-embed-link {
        display: none !important; /* cause */
    }

    body > :not(.print) {
        display: none !important; /* cause */
    }
```

I tried injecting code in the last `style` tag to override it. No luck. Maybe with a [cascade layer](https://css-tricks.com/css-cascade-layers/)?
